import time

from inferencePipeline import loadPipeline


QUESTION_BANK = [
    # --- Geography (70 Questions) ---
    {"questionID": 301, "question": "What is the capital of Greece?"},
    {"questionID": 302, "question": "What is the capital of Thailand?"},
    {"questionID": 303, "question": "What is the capital of South Korea?"},
    {"questionID": 304, "question": "What is the capital of Portugal?"},
    {"questionID": 305, "question": "What is the capital of Finland?"},
    {"questionID": 306, "question": "What is the capital of Peru?"},
    {"questionID": 307, "question": "What is the capital of Colombia?"},
    {"questionID": 308, "question": "What is the capital of Nigeria?"},
    {"questionID": 309, "question": "What is the capital of Saudi Arabia?"},
    {"questionID": 310, "question": "What is the capital of Vietnam?"},
    {"questionID": 311, "question": "What is the capital of Poland?"},
    {"questionID": 312, "question": "What is the capital of Austria?"},
    {"questionID": 313, "question": "What is the capital of Denmark?"},
    {"questionID": 314, "question": "What is the capital of Hungary?"},
    {"questionID": 315, "question": "What is the capital of Chile?"},
    {"questionID": 316, "question": "What is the capital of the Philippines?"},
    {"questionID": 317, "question": "What is the capital of New Zealand?"},
    {"questionID": 318, "question": "What is the capital of Kenya?"},
    {"questionID": 319, "question": "What is the capital of Morocco?"},
    {"questionID": 320, "question": "What is the capital of Argentina?"},
    {"questionID": 321, "question": "What is the longest river in South America?"},
    {"questionID": 322, "question": "What is the longest river in North America?"},
    {"questionID": 323, "question": "What is the longest river in Asia?"},
    {"questionID": 324, "question": "What is the longest river in Europe?"},
    {"questionID": 325, "question": "What is the world's highest mountain?"},
    {"questionID": 326, "question": "What is the highest mountain in Africa?"},
    {"questionID": 327, "question": "What is the highest mountain in North America?"},
    {"questionID": 328, "question": "In which country is Mount Kilimanjaro located?"},
    {"questionID": 329, "question": "In which country is Mount Fuji located?"},
    {"questionID": 330, "question": "What is the largest (by area) continent?"},
    {"questionID": 331, "question": "What is the smallest (by area) continent?"},
    {"questionID": 332, "question": "What is the largest (by area) country in the world?"},
    {"questionID": 333, "question": "What is the largest (by population) country in the world?"},
    {"questionID": 334, "question": "What is the world's largest hot desert?"},
    {"questionID": 335, "question": "What is the world's largest cold desert?"},
    {"questionID": 336, "question": "What is the largest ocean in the world?"},
    {"questionID": 337, "question": "What is the smallest ocean in the world?"},
    {"questionID": 338, "question": "Which sea is the largest inland sea in the world?"},
    {"questionID": 339, "question": "In which country is the ancient city of Petra?"},
    {"questionID": 340, "question": "In which country is the ancient city of Machu Picchu?"},
    {"questionID": 341, "question": "In which country is Angkor Wat located?"},
    {"questionID": 342, "question": "Which country is known as the 'Land of the Rising Sun'?"},
    {"questionID": 343, "question": "Which country is known as the 'Land Down Under'?"},
    {"questionID": 344, "question": "What body of water separates the UK from France?"},
    {"questionID": 345, "question": "What is the name of the strait that separates Spain and Morocco?"},
    {"questionID": 346, "question": "What is the largest island in the world?"},
    {"questionID": 347, "question": "What is the largest lake in Africa?"},
    {"questionID": 348, "question": "What is the deepest lake in the world?"},
    {"questionID": 349, "question": "Which two South American countries are landlocked?"},
    {"questionID": 350, "question": "What is the name of the waterfall on the border of Zambia and Zimbabwe?"},
    {"questionID": 351, "question": "Through which major U.S. city does the Mississippi River flow?"},
    {"questionID": 352, "question": "Which European city is divided by the Danube River?"},
    {"questionID": 353, "question": "The Andes mountains run along the west coast of which continent?"},
    {"questionID": 354, "question": "The Ural Mountains are traditionally considered the boundary between which two continents?"},
    {"questionID": 355, "question": "What is the northernmost capital city in the world?"},
    {"questionID": 356, "question": "Which desert covers much of Botswana and parts of Namibia and South Africa?"},
    {"questionID": 357, "question": "Which major river flows through London?"},
    {"questionID": 358, "question": "Which major river flows through Paris?"},
    {"questionID": 359, "question": "Which major river flows through Rome?"},
    {"questionID": 360, "question": "What is the largest state in the USA by area?"},
    {"questionID": 361, "question": "What is the most populous state in the USA?"},
    {"questionID": 362, "question": "Which country borders both the Atlantic and Pacific oceans?"},
    {"questionID": 363, "question": "Which country borders both the Mediterranean Sea and the Black Sea?"},
    {"questionID": 364, "question": "What is the name of the large archipelago in Southeast Asia that includes Indonesia and the Philippines?"},
    {"questionID": 365, "question": "The Panama Canal connects which two oceans?"},
    {"questionID": 366, "question": "The Suez Canal connects which two seas?"},
    {"questionID": 367, "question": "What is the 'Ring of Fire'?"},
    {"questionID": 368, "question": "In which country would you find the city of Barcelona?"},
    {"questionID": 369, "question": "In which country would you find the city of Toronto?"},
    {"questionID": 370, "question": "In which country would you find the city of St. Petersburg?"},

    # --- History (70 Questions) ---
    {"questionID": 401, "question": "Who was the Roman general who conquered Gaul and became dictator of Rome?"},
    {"questionID": 402, "question": "What was the period of cultural, artistic, and intellectual 'rebirth' in Europe?"},
    {"questionID": 403, "question": "In what year did the French Revolution begin?"},
    {"questionID": 404, "question": "Who was the leader of the Soviet Union during World War II?"},
    {"questionID": 405, "question": "Which civilization is credited with inventing the first writing system, cuneiform?"},
    {"questionID": 406, "question": "Who was the first emperor of Rome?"},
    {"questionID": 407, "question": "In what year did Christopher Columbus first reach the Americas?"},
    {"questionID": 408, "question": "Who wrote 'The Ninety-Five Theses', sparking the Protestant Reformation?"},
    {"questionID": 409, "question": "Which war was fought between Athens and Sparta?"},
    {"questionID": 410, "question": "Who founded the Mongol Empire?"},
    {"questionID": 411, "question": "What battle in 1066 led to the Norman conquest of England?"},
    {"questionID": 412, "question": "Who was the queen of France who famously said 'Let them eat cake'?"},
    {"questionID": 413, "question": "What event started World War II in Europe?"},
    {"questionID": 414, "question": "In what year did World War II end?"},
    {"questionID": 415, "question": "What event brought the United States into World War II?"},
    {"questionID": 416, "question": "Who was the U.S. President during the American Civil War?"},
    {"questionID": 417, "question": "What document, signed in 1215, limited the power of the English king?"},
    {"questionID": 418, "question": "Who was the first person to circumnavigate the globe?"},
    {"questionID": 419, "question": "What was the 'Cold War'?"},
    {"questionID": 420, "question": "What was the 'Iron Curtain'?"},
    {"questionID": 421, "question": "Who led the movement for Indian independence from Britain?"},
    {"questionID": 422, "question": "What system of racial segregation existed in South Africa?"},
    {"questionID": 423, "question": "Who was the first President of the United States?"},
    {"questionID": 424, "question": "In what city was Archduke Franz Ferdinand assassinated?"},
    {"questionID": 425, "question": "Who painted the Mona Lisa?"},
    {"questionID": 426, "question": "Who painted the ceiling of the Sistine Chapel?"},
    {"questionID": 427, "question": "Which empire was ruled by Suleiman the Magnificent?"},
    {"questionID": 428, "question": "Which Chinese dynasty built the Great Wall's most famous sections?"},
    {"questionID": 429, "question": "What was the name of the ship that carried the Pilgrims to America in 1620?"},
    {"questionID": 430, "question": "What battle, fought in 1815, marked the final defeat of Napoleon Bonaparte?"},
    {"questionID": 431, "question": "Who was the first woman to fly solo across the Atlantic Ocean?"},
    {"questionID": 432, "question": "What was the 'Black Death'?"},
    {"questionID": 433, "question": "Who was the first person to walk on the moon?"},
    {"questionID": 434, "question": "In what year did the first man walk on the moon?"},
    {"questionID": 435, "question": "What was the name of the U.S. project to build the atomic bomb?"},
    {"questionID": 436, "question": "Which two Japanese cities were hit by atomic bombs?"},
    {"questionID": 437, "question": "Who was the pharaoh for whom the Great Pyramid of Giza was built?"},
    {"questionID": 438, "question": "Which Greek philosopher was the teacher of Alexander the Great?"},
    {"questionID": 439, "question": "What was the 'Renaissance'?"},
    {"questionID": 440, "question": "Who invented the printing press with movable type in Europe?"},
    {"questionID": 441, "question": "What was the 'Industrial Revolution'?"},
    {"questionID": 442, "question": "Which country gifted the Statue of Liberty to the USA?"},
    {"questionID": 443, "question": "Who was the leader of the Bolshevik Revolution in Russia?"},
    {"questionID": 444, "question": "In what year did the Titanic sink?"},
    {"questionID": 445, "question": "What was the 'Space Race'?"},
    {"questionID": 446, "question": "Who was the leader of the Cuban Revolution?"},
    {"questionID": 447, "question": "What was the 'Enlightenment'?"},
    {"questionID": 448, "question": "Which war was fought between the North and South in the United States?"},
    {"questionID": 449, "question": "Who was the British Prime Minister during World War II?"},
    {"questionID": 450, "question": "What was the name of the ancient trade route connecting the East and West?"},
    {"questionID": 451, "question": "Who was the longest-reigning British monarch?"},
    {"questionID": 452, "question": "What was the 'Scramble for Africa'?"},
    {"questionID": 453, "question": "Which empire conquered Constantinople in 1453?"},
    {"questionID": 454, "question": "Who wrote 'The Communist Manifesto'?"},
    {"questionID": 456, "question": "In what year did the American colonies declare independence?"},
    {"questionID": 457, "question": "Who was the 'Sun King' of France?"},
    {"questionID": 458, "question": "What was the 'Bay of Pigs Invasion'?"},
    {"questionID": 459, "question": "Which ancient civilization built the Colosseum?"},
    {"questionID": 460, "question": "Which ancient civilization is associated with philosophers like Socrates, Plato, and Aristotle?"},
    {"questionID": 461, "question": "What was the 'Hundred Years' War' fought between?"},
    {"questionID": 462, "question": "Who was the leader of the civil rights movement in the United States known for his 'I Have a Dream' speech?"},
    {"questionID": 463, "question": "What empire did Alexander the Great rule?"},
    {"questionID": 464, "question": "What was the last dynasty to rule China?"},
    {"questionID": 465, "question": "Who was the first female pharaoh of Egypt?"},
    {"questionID": 466, "question": "What was the 'Opium War'?"},
    {"questionID": 467, "question": "What ancient city was destroyed by the eruption of Mount Vesuvius in 79 AD?"},
    {"questionID": 468, "question": "Who was the first emperor of Japan?"},
    {"questionID": 469, "question": "What was the 'Vikings'?"},
    {"questionID": 470, "question": "Who was the first President of South Africa elected after apartheid?"},

    # --- Algebra (60 Questions) ---
    {"questionID": 501, "question": "Solve for x: 2x + 3 = 13."},
    {"questionID": 502, "question": "Solve for y: 5y - 4 = 21."},
    {"questionID": 503, "question": "Solve for z: z / 4 = 5."},
    {"questionID": 504, "question": "Solve for x: x / 3 + 1 = 7."},
    {"questionID": 505, "question": "Solve for a: 3(a + 2) = 15."},
    {"questionID": 506, "question": "Solve for b: 2b + 10 = 4b."},
    {"questionID": 507, "question": "Solve for x: 5x - 8 = 2x + 1."},
    {"questionID": 508, "question": "Solve for y: (y + 5) / 2 = 8."},
    {"questionID": 509, "question": "Solve for x: 10 - x = 4."},
    {"questionID": 510, "question": "Solve for z: 7z = 84."},
    {"questionID": 511, "question": "Solve the inequality: 2x + 1 > 7."},
    {"questionID": 512, "question": "Solve the inequality: 3x - 5 <= 10."},
    {"questionID": 513, "question": "Solve the inequality: 10 - x > 4."},
    {"questionID": 514, "question": "Solve the inequality: y / 3 + 2 < 5."},
    {"questionID": 515, "question": "Solve the inequality: 4z >= 16."},
    {"questionID": 516, "question": "Factor the expression: x^2 - 16."},
    {"questionID": 517, "question": "Factor the expression: y^2 - 81."},
    {"questionID": 518, "question": "Factor the expression: x^2 + 6x + 9."},
    {"questionID": 519, "question": "Factor the expression: a^2 - 10a + 25."},
    {"questionID": 520, "question": "Factor the expression: x^2 + 5x + 6."},
    {"questionID": 521, "question": "Factor the expression: b^2 - b - 12."},
    {"questionID": 522, "question": "Factor the expression: 2x^2 - 8."},
    {"questionID": 523, "question": "Factor the expression: 3y^2 + 9y."},
    {"questionID": 524, "question": "Factor the expression: x^2 - 49."},
    {"questionID": 525, "question": "Factor the expression: y^2 + 8y + 15."},
    {"questionID": 526, "question": "Solve for x: x^2 = 64."},
    {"questionID": 527, "question": "Solve for x: x^2 = 121."},
    {"questionID": 528, "question": "What are the solutions to x^2 - 25 = 0?"},
    {"questionID": 529, "question": "What are the solutions to x^2 - 8x + 16 = 0?"},
    {"questionID": 530, "question": "What are the solutions to x^2 + 2x - 8 = 0?"},
    {"questionID": 531, "question": "What are the solutions to x^2 - 9x + 20 = 0?"},
    {"questionID": 532, "question": "What are the solutions to y^2 - 1 = 0?"},
    {"questionID": 533, "question": "What are the solutions to a^2 + 4a + 3 = 0?"},
    {"questionID": 534, "question": "What are the solutions to 2x^2 - 2 = 0?"},
    {"questionID": 535, "question": "What are the solutions to x(x - 5) = 0?"},
    {"questionID": 536, "question": "Simplify the expression: 3(x + 4) + 2x."},
    {"questionID": 537, "question": "Simplify the expression: 5(y - 2) - y."},
    {"questionID": 538, "question": "Simplify the expression: 2a + 3b - a + b."},
    {"questionID": 539, "question": "Simplify the expression: x(x + 2) + x^2."},
    {"questionID": 540, "question": "Simplify the expression: (x + 3)(x + 2)."},
    {"questionID": 541, "question": "Simplify the expression: (y - 4)(y + 4)."},
    {"questionID": 542, "question": "Simplify the expression: (x + 5)^2."},
    {"questionID": 543, "question": "Simplify the expression: 10x - 2(3x + 1)."},
    {"questionID": 544, "question": "Simplify the expression: (2x^2 + 5x) - (x^2 - 3x)."},
    {"questionID": 545, "question": "Simplify the expression: 8a + 2(b - 3a)."},
    {"questionID": 546, "question": "If f(x) = 3x - 1, what is f(4)?"},
    {"questionID": 547, "question": "If f(x) = 5x + 10, what is f(-1)?"},
    {"questionID": 548, "question": "If f(x) = x^2 + 1, what is f(3)?"},
    {"questionID": 549, "question": "If f(x) = 10 - 2x, what is f(0)?"},
    {"questionID": 550, "question": "If g(x) = 2x^2 - 3, what is g(2)?"},
    {"questionID": 551, "question": "What is the slope of the line y = 4x + 7?"},
    {"questionID": 552, "question": "What is the slope of the line 2y = 6x - 4?"},
    {"questionID": 553, "question": "What is the y-intercept of the line y = -2x + 5?"},
    {"questionID": 554, "question": "What is the slope of the line 3x + y = 10?"},
    {"questionID": 555, "question": "What is the slope of the line passing through (1, 2) and (3, 6)?"},
    {"questionID": 556, "question": "What is the slope of the line passing through (0, 5) and (2, 5)?"},
    {"questionID": 557, "question": "Solve for x: 1.5x = 6."},
    {"questionID": 558, "question": "Solve for y: y / 0.5 = 10."},
    {"questionID": 559, "question": "Solve the system: y = x + 1 and y = 2x - 1."},
    {"questionID": 560, "question": "Solve the system: x + y = 10 and x - y = 4."},
]


def main():
    """Load the inference pipeline, run it, and report elapsed time."""
    questions = QUESTION_BANK

    # Load the inference pipeline
    pipeline = loadPipeline()

    # Start time
    start_time = time.perf_counter()

    # Run the inference pipeline
    answers = pipeline(questions)

    # Elapsed time
    elapsed_time = time.perf_counter() - start_time

    print(answers)
    print(f"Elapsed time: {elapsed_time:.2f}s")


if __name__ == "__main__":
    main()
